source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BLListViewController_Example', :exclusive => true do
  pod 'BLListViewController', :path => '../'
  pod 'BLParseFetch'
end

target 'BLListViewController_Tests', :exclusive => true do
  pod 'BLListViewController', :path => '../'

  
end
